# Generated by Django 4.0.3 on 2022-05-18 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.TextField(max_length=1024, primary_key=True, serialize=False)),
                ('Receive_Time', models.CharField(max_length=100)),
                ('Severity', models.CharField(max_length=100)),
                ('Event_Type_ID', models.CharField(max_length=100)),
                ('Event_Name', models.CharField(max_length=100)),
                ('Device', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=100)),
                ('Source_Service', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Destination_Service', models.CharField(max_length=100)),
                ('Action', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Event_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='matrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_by_order', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Destination_Service', models.CharField(max_length=100)),
                ('Action', models.CharField(max_length=100)),
                ('Number_of_hits', models.IntegerField()),
            ],
        ),
    ]
