# Generated by Django 4.0.3 on 2022-06-30 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receive_Time', models.CharField(max_length=100)),
                ('Severity', models.CharField(max_length=100)),
                ('Event_Name', models.CharField(max_length=100)),
                ('Device', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Action', models.CharField(max_length=100)),
                ('proto', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=0)),
                ('is_sm_ips_ports', models.IntegerField(default=0)),
                ('dwin', models.IntegerField(default=0)),
                ('dttl', models.IntegerField(default=0)),
                ('dtcpb', models.IntegerField(default=0)),
                ('dpkts', models.IntegerField(default=0)),
                ('dmean', models.IntegerField(default=0)),
                ('dloss', models.IntegerField(default=0)),
                ('dbytes', models.IntegerField(default=0)),
                ('ct_srv_src', models.IntegerField(default=0)),
                ('ct_srv_dst', models.IntegerField(default=0)),
                ('ct_src_ltm', models.IntegerField(default=0)),
                ('ct_src_dport_ltm', models.IntegerField(default=0)),
                ('ct_dst_src_ltm', models.IntegerField(default=0)),
                ('ct_dst_sport_ltm', models.IntegerField(default=0)),
                ('ct_dst_ltm', models.IntegerField(default=0)),
                ('sbytes', models.IntegerField(default=0)),
                ('sloss', models.IntegerField(default=0)),
                ('smean', models.IntegerField(default=0)),
                ('spkts', models.IntegerField(default=0)),
                ('stcpb', models.IntegerField(default=0)),
                ('sttl', models.IntegerField(default=0)),
                ('swin', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('ackdat', models.FloatField(default=0)),
                ('dinpkt', models.FloatField(default=0)),
                ('djit', models.FloatField(default=0)),
                ('dload', models.FloatField(default=0)),
                ('dur', models.FloatField(default=0)),
                ('sinpkt', models.FloatField(default=0)),
                ('sjit', models.FloatField(default=0)),
                ('sload', models.FloatField(default=0)),
                ('synack', models.FloatField(default=0)),
                ('tcprtt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='matrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupeByValue', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('data', models.JSONField(default='{}')),
            ],
        ),
    ]
