# Generated by Django 4.0.3 on 2022-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrices',
            name='Action',
        ),
        migrations.RemoveField(
            model_name='matrices',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='matrices',
            name='Destination_Service',
        ),
        migrations.RemoveField(
            model_name='matrices',
            name='Number_of_hits',
        ),
        migrations.RemoveField(
            model_name='matrices',
            name='Source',
        ),
        migrations.RemoveField(
            model_name='matrices',
            name='group_by_order',
        ),
        migrations.AddField(
            model_name='matrices',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
